/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 7.1.2   2017-05-31

The MIT License (MIT)
Copyright (c) 2009-2017 Atollic AB

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f4xx.h"
#include "stm32f4_discovery.h"
#include "initial_ization.h"

/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/


void ADC_IRQHandler();
void TIM2_IRQHandler();

int main(void)
{
  /*****************************This came with project just gona leave for now*******************************/
  /* Initialize LEDs */
  STM_EVAL_LEDInit(LED3);
  STM_EVAL_LEDInit(LED4);
  STM_EVAL_LEDInit(LED5);
  STM_EVAL_LEDInit(LED6);

  /* Turn on LEDs */
  STM_EVAL_LEDOn(LED3);
  STM_EVAL_LEDOn(LED4);
  STM_EVAL_LEDOn(LED5);
  STM_EVAL_LEDOn(LED6);
  /**
  *  IMPORTANT NOTE!
  *  The symbol VECT_TAB_SRAM needs to be defined when building the project
  *  if code has been located to RAM and interrupts are used. 
  *  Otherwise the interrupt table located in flash will be used.
  *  See also the <system_*.c> file and how the SystemInit() function updates 
  *  SCB->VTOR register.  
  *  E.g.  SCB->VTOR = 0x20000000;  
  */




  /**************************** Run Initialization functions and start timer************************************/

  init_rcc();					//turn on peripheral busses
  init_pins();					//initialize pins
  init_timer2();				//initialize tim2 for ADC conversion pace
  init_dma();					//initialize DMA for ADC
  init_adc();					//initialize ADC

  // Initialize variables for ADC conversions
  volatile uint16_t vfo_amp = ADC1ConvertedValue[0];
  volatile uint16_t vfo_freq = ADC1ConvertedValue[1];
  volatile uint16_t lfo_amp = ADC1ConvertedValue[2];
  volatile uint16_t lfo_freq = ADC1ConvertedValue[3];
  volatile uint16_t volume = ADC1ConvertedValue[4];
  volatile uint16_t env_attack = ADC1ConvertedValue[5];
  volatile uint16_t env_decay = ADC1ConvertedValue[6];
  volatile uint16_t env_sustain = ADC1ConvertedValue[7];
  volatile uint16_t env_release = ADC1ConvertedValue[8];
  volatile uint16_t fc_low = ADC1ConvertedValue[9];
  volatile uint16_t fc_high = ADC1ConvertedValue[10];
  volatile uint16_t fc_resonance = ADC1ConvertedValue[11];
  volatile uint16_t gain = ADC1ConvertedValue[12];


  TIM_Cmd(TIM2, ENABLE);		//start timer


  int i = 0;

  uint16_t test;


  /* Infinite loop */
  while (1)
  {
	//  printf("vfo_amp  vfo_freq  lfo_amp  lfo_freq  volume  env_attack  env_decay  env_sustain  env_release  fc_low  fc_high  fc_resonance  gain\n");
//	printf("   %u       %u        %u	   %u		%u		  %u		 %u			%u			  %u		 %u		  %u		%u			%u\n", (unsigned int)vfo_amp, (unsigned int)vfo_freq, (unsigned int)lfo_amp, (unsigned int)lfo_freq, (unsigned int)volume, (unsigned int)env_attack, (unsigned int)env_decay, (unsigned int)env_sustain, (unsigned int)env_release, (unsigned int)fc_low, (unsigned int)fc_high, (unsigned int)fc_resonance, (unsigned int)gain);

	  test = vfo_amp;
	  test = vfo_freq;
	  test = lfo_amp;
	  test = lfo_freq;
	  test = volume;
	  test = env_attack;
	  test = env_decay;
	  test = env_sustain;
	  test = env_release;
	  test = fc_low;
	  test = fc_high;
	  test = fc_resonance;
	  test = gain;


	// Waste some time
	for (i = 0; i < 5000000; i++){

	}
  }
}


/*
 * Callback used by stm32f4_discovery_audio_codec.c.
 * Refer to stm32f4_discovery_audio_codec.h for more info.
 */
void EVAL_AUDIO_TransferComplete_CallBack(uint32_t pBuffer, uint32_t Size){
  /* TODO, implement your code here */
  return;
}

/*
 * Callback used by stm324xg_eval_audio_codec.c.
 * Refer to stm324xg_eval_audio_codec.h for more info.
 */
uint16_t EVAL_AUDIO_GetSampleCallBack(void){
  /* TODO, implement your code here */
  return -1;
}








/**********************************************Interrupt handlers**********************************/
//Not sure if i can keep these in the other files so i put em in the main
void TIM2_IRQHandler(){
	TIM_ClearITPendingBit(TIM2, TIM_IT_Update);
}

// set up yet but might to see if the adc is working
void ADC_IRQHandler() {
        /* acknowledge interrupt */
        ADC_ClearITPendingBit(ADC1, ADC_IT_EOC);
}

